name: Test
on:
  push:
  pull_request:
  schedule:
  - cron: '2 1 * * 6'  # M H d m w (Saturdays at 1:02)
jobs:
  check:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    runs-on: ubuntu-latest
    name: check
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: set PYSHA
      run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: dependencies
      run: pip install -U pre-commit
    - uses: reviewdog/action-setup@v1
    - if: github.event_name != 'schedule'
      name: comment
      run: |
        if [[ $EVENT == pull_request ]]; then
          REPORTER=github-pr-review
        else
          REPORTER=github-check
        fi
        pre-commit run -a todo | reviewdog -efm="%f:%l: %m" -name=TODO -tee -reporter=$REPORTER -filter-mode nofilter
        pre-commit run -a flake8 | reviewdog -f=pep8 -name=flake8 -tee -reporter=$REPORTER -filter-mode nofilter
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT: ${{ github.event_name }}
    - run: pre-commit run -a --show-diff-on-failure
  test-os:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    strategy:
      matrix:
        python: [2.7, 3.7]
        os: [macos-latest, windows-latest]
    name: py${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install
      shell: bash
      run: |
        pip install -U tox
        mkdir -p "$HOME/bin"
        curl -sfL https://coverage.codacy.com/get.sh > "$HOME/bin/codacy"
        chmod +x "$HOME/bin/codacy"
        echo "$HOME/bin" >> $GITHUB_PATH
    - run: tox -e py${PYVER/./}
      shell: bash
      env:
        PYVER: ${{ matrix.python }}
        COVERALLS_FLAG_NAME: py${{ matrix.python }}-${{ matrix.os }}
        COVERALLS_PARALLEL: true
        COVERALLS_SERVICE_NAME: github
        # coveralls needs explicit token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  test:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
    name: py${{ matrix.python }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install
      run: |
        pip install -U tox
        mkdir -p "$HOME/bin"
        curl -sfL https://coverage.codacy.com/get.sh > "$HOME/bin/codacy"
        chmod +x "$HOME/bin/codacy"
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: tox
      run: |
        if [[ "$PYVER" == py* ]]; then
          tox -e $PYVER                                             # basic:pypy
        elif [[ "$PYVER" == *3.9 ]]; then
          tox -e py${PYVER/./}                                      # basic
        elif [[ "$PYVER" == "3.7" ]]; then
          tox -e py${PYVER/./}-tf,py${PYVER/./}-tf-keras            # full
        else
          tox -e py${PYVER/./}-tf-keras                             # normal
        fi
      env:
        PYVER: ${{ matrix.python }}
        COVERALLS_FLAG_NAME: py${{ matrix.python }}
        COVERALLS_PARALLEL: true
        COVERALLS_SERVICE_NAME: github
        # coveralls needs explicit token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  finish:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    name: pytest cov
    continue-on-error: ${{ github.event_name != 'push' }}
    needs: [test, test-os]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - name: Coveralls Finished
      run: |
        pip install -U coveralls
        coveralls --finish || :
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Codacy Finished
      run: |
        curl -sfL https://coverage.codacy.com/get.sh > codacy
        bash codacy final || :
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  deploy:
    needs: [check, test, test-os]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        sudo apt-get install -yqq pandoc
        pip install -r .meta/requirements-build.txt
        make build .dockerignore Dockerfile snapcraft.yaml
    - id: dist
      uses: casperdcl/deploy-pypi@v2
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        gpg_key: ${{ secrets.GPG_KEY }}
        upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
    - id: collect_assets
      name: Collect assets
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          echo ::set-output name=docker_tags::latest,${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=snap_channel::stable,candidate,edge
        elif [[ $GITHUB_REF == refs/heads/master ]]; then
          echo ::set-output name=docker_tags::master
          echo ::set-output name=snap_channel::candidate,edge
        elif [[ $GITHUB_REF == refs/heads/devel ]]; then
          echo ::set-output name=docker_tags::devel
          echo ::set-output name=snap_channel::edge
        fi
        git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD > _CHANGES.md
    - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        release_name: tqdm ${{ github.ref }} stable
        body_path: _CHANGES.md
        draft: true
        files: |
          dist/${{ steps.dist.outputs.whl }}
          dist/${{ steps.dist.outputs.whl_asc }}
    - uses: snapcore/action-build@v1
      id: snap_build
    - if: github.event_name == 'push' && steps.collect_assets.outputs.snap_channel
      uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAP_TOKEN }}
        snap: ${{ steps.snap_build.outputs.snap }}
        release: ${{ steps.collect_assets.outputs.snap_channel }}
    - name: Docker build push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.repository }}
        tags: ${{ steps.collect_assets.outputs.docker_tags }}
        password: ${{ secrets.DOCKER_PWD }}
        username: ${{ secrets.DOCKER_USR }}
        no_push: ${{ steps.collect_assets.outputs.docker_tags == '' }}
    - name: Docker push GitHub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.repository }}/tqdm
        tags: ${{ steps.collect_assets.outputs.docker_tags }}
        password: ${{ github.token }}
        username: ${{ github.actor }}
        registry: docker.pkg.github.com
        no_push: ${{ steps.collect_assets.outputs.docker_tags == '' }}
